/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OptRuntimeModule extends AbstractOptRuntimeModule {
}
