/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.ui.contentassist;

import org.xtext.example.opt.ui.contentassist.AbstractOptProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OptProposalProvider extends AbstractOptProposalProvider {
}
