/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.xtext.example.opt.ide.contentassist.antlr.OptParser;
import org.xtext.example.opt.ide.contentassist.antlr.internal.InternalOptLexer;

/**
 * Manual modifications go to {@link OptWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractOptWebModule extends DefaultWebModule {

	public AbstractOptWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalOptLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return OptParser.class;
	}
	
}
