/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.scoping;

import org.xtext.example.opt.scoping.AbstractOptScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class OptScopeProvider extends AbstractOptScopeProvider {
}
