/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOptScopeProvider extends DelegatingScopeProvider {
}
