/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.opt.opt.Expression;
import org.xtext.example.opt.opt.Function;
import org.xtext.example.opt.opt.OptPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.impl.FunctionImpl#getFunction1 <em>Function1</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class FunctionImpl extends TypeImpl implements Function
{
  /**
   * The cached value of the '{@link #getFunction1() <em>Function1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunction1()
   * @generated
   * @ordered
   */
  protected Expression function1;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OptPackage.Literals.FUNCTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getFunction1()
  {
    return function1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFunction1(Expression newFunction1, NotificationChain msgs)
  {
    Expression oldFunction1 = function1;
    function1 = newFunction1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OptPackage.FUNCTION__FUNCTION1, oldFunction1, newFunction1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFunction1(Expression newFunction1)
  {
    if (newFunction1 != function1)
    {
      NotificationChain msgs = null;
      if (function1 != null)
        msgs = ((InternalEObject)function1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OptPackage.FUNCTION__FUNCTION1, null, msgs);
      if (newFunction1 != null)
        msgs = ((InternalEObject)newFunction1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OptPackage.FUNCTION__FUNCTION1, null, msgs);
      msgs = basicSetFunction1(newFunction1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptPackage.FUNCTION__FUNCTION1, newFunction1, newFunction1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OptPackage.FUNCTION__FUNCTION1:
        return basicSetFunction1(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OptPackage.FUNCTION__FUNCTION1:
        return getFunction1();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OptPackage.FUNCTION__FUNCTION1:
        setFunction1((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OptPackage.FUNCTION__FUNCTION1:
        setFunction1((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OptPackage.FUNCTION__FUNCTION1:
        return function1 != null;
    }
    return super.eIsSet(featureID);
  }

} //FunctionImpl
