/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.opt.opt.OptPackage;
import org.xtext.example.opt.opt.OptimizationMethod;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Optimization Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class OptimizationMethodImpl extends MinimalEObjectImpl.Container implements OptimizationMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptimizationMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OptPackage.Literals.OPTIMIZATION_METHOD;
  }

} //OptimizationMethodImpl
