/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.opt.opt.OptPackage;
import org.xtext.example.opt.opt.Stopping_Criteria;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Stopping Criteria</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class Stopping_CriteriaImpl extends MinimalEObjectImpl.Container implements Stopping_Criteria
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Stopping_CriteriaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OptPackage.Literals.STOPPING_CRITERIA;
  }

} //Stopping_CriteriaImpl
