/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.opt.ui.internal.OptActivator;

public class OptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OptActivator.getInstance().getInjector("org.xtext.example.opt.Opt");
	}

}
