/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.opt.ui.AbstractOptUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OptUiModule extends AbstractOptUiModule {
  public OptUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
