/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt;

import org.xtext.example.opt.AbstractOptRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OptRuntimeModule extends AbstractOptRuntimeModule {
}
