/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt;

import org.xtext.example.opt.OptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OptStandaloneSetup extends OptStandaloneSetupGenerated {
  public static void doSetup() {
    OptStandaloneSetup _optStandaloneSetup = new OptStandaloneSetup();
    _optStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
