/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.opt.parser.antlr.internal.InternalOptParser;
import org.xtext.example.opt.services.OptGrammarAccess;

public class OptParser extends AbstractAntlrParser {

	@Inject
	private OptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOptParser createParser(XtextTokenStream stream) {
		return new InternalOptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
