/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Convergence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.Convergence#getConvergenceThreshold <em>Convergence Threshold</em>}</li>
 *   <li>{@link org.xtext.example.opt.opt.Convergence#getConvergencerange <em>Convergencerange</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getConvergence()
 * @model
 * @generated
 */
public interface Convergence extends Type, Stopping_Criteria
{
  /**
   * Returns the value of the '<em><b>Convergence Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Convergence Threshold</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convergence Threshold</em>' attribute.
   * @see #setConvergenceThreshold(int)
   * @see org.xtext.example.opt.opt.OptPackage#getConvergence_ConvergenceThreshold()
   * @model
   * @generated
   */
  int getConvergenceThreshold();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Convergence#getConvergenceThreshold <em>Convergence Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Convergence Threshold</em>' attribute.
   * @see #getConvergenceThreshold()
   * @generated
   */
  void setConvergenceThreshold(int value);

  /**
   * Returns the value of the '<em><b>Convergencerange</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Convergencerange</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Convergencerange</em>' attribute.
   * @see #setConvergencerange(int)
   * @see org.xtext.example.opt.opt.OptPackage#getConvergence_Convergencerange()
   * @model
   * @generated
   */
  int getConvergencerange();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Convergence#getConvergencerange <em>Convergencerange</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Convergencerange</em>' attribute.
   * @see #getConvergencerange()
   * @generated
   */
  void setConvergencerange(int value);

} // Convergence
