/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Duration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.Duration#getDurationtime <em>Durationtime</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getDuration()
 * @model
 * @generated
 */
public interface Duration extends Type, Stopping_Criteria
{
  /**
   * Returns the value of the '<em><b>Durationtime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Durationtime</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Durationtime</em>' attribute.
   * @see #setDurationtime(String)
   * @see org.xtext.example.opt.opt.OptPackage#getDuration_Durationtime()
   * @model
   * @generated
   */
  String getDurationtime();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Duration#getDurationtime <em>Durationtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Durationtime</em>' attribute.
   * @see #getDurationtime()
   * @generated
   */
  void setDurationtime(String value);

} // Duration
