/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.EndTime#getEndtime <em>Endtime</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getEndTime()
 * @model
 * @generated
 */
public interface EndTime extends Type, Stopping_Criteria
{
  /**
   * Returns the value of the '<em><b>Endtime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Endtime</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endtime</em>' attribute.
   * @see #setEndtime(String)
   * @see org.xtext.example.opt.opt.OptPackage#getEndTime_Endtime()
   * @model
   * @generated
   */
  String getEndtime();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.EndTime#getEndtime <em>Endtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Endtime</em>' attribute.
   * @see #getEndtime()
   * @generated
   */
  void setEndtime(String value);

} // EndTime
