/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.Function#getFunction1 <em>Function1</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends Type, Objective
{
  /**
   * Returns the value of the '<em><b>Function1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function1</em>' containment reference.
   * @see #setFunction1(Expression)
   * @see org.xtext.example.opt.opt.OptPackage#getFunction_Function1()
   * @model containment="true"
   * @generated
   */
  Expression getFunction1();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Function#getFunction1 <em>Function1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function1</em>' containment reference.
   * @see #getFunction1()
   * @generated
   */
  void setFunction1(Expression value);

} // Function
