/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Max Iteration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.MaxIteration#getMaxiteration <em>Maxiteration</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getMaxIteration()
 * @model
 * @generated
 */
public interface MaxIteration extends Type, Stopping_Criteria
{
  /**
   * Returns the value of the '<em><b>Maxiteration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Maxiteration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maxiteration</em>' attribute.
   * @see #setMaxiteration(int)
   * @see org.xtext.example.opt.opt.OptPackage#getMaxIteration_Maxiteration()
   * @model
   * @generated
   */
  int getMaxiteration();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.MaxIteration#getMaxiteration <em>Maxiteration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maxiteration</em>' attribute.
   * @see #getMaxiteration()
   * @generated
   */
  void setMaxiteration(int value);

} // MaxIteration
