/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objective</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.opt.opt.OptPackage#getObjective()
 * @model
 * @generated
 */
public interface Objective extends EObject
{
} // Objective
