/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optimization Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.opt.opt.OptPackage#getOptimizationMethod()
 * @model
 * @generated
 */
public interface OptimizationMethod extends EObject
{
} // OptimizationMethod
