/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optimizer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.opt.opt.Optimizer#getObjective <em>Objective</em>}</li>
 *   <li>{@link org.xtext.example.opt.opt.Optimizer#getStoppingcriteria <em>Stoppingcriteria</em>}</li>
 *   <li>{@link org.xtext.example.opt.opt.Optimizer#getOptimizationmethod <em>Optimizationmethod</em>}</li>
 *   <li>{@link org.xtext.example.opt.opt.Optimizer#getSeed <em>Seed</em>}</li>
 *   <li>{@link org.xtext.example.opt.opt.Optimizer#getMinmax <em>Minmax</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.opt.opt.OptPackage#getOptimizer()
 * @model
 * @generated
 */
public interface Optimizer extends Type
{
  /**
   * Returns the value of the '<em><b>Objective</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective</em>' reference.
   * @see #setObjective(Objective)
   * @see org.xtext.example.opt.opt.OptPackage#getOptimizer_Objective()
   * @model
   * @generated
   */
  Objective getObjective();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Optimizer#getObjective <em>Objective</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective</em>' reference.
   * @see #getObjective()
   * @generated
   */
  void setObjective(Objective value);

  /**
   * Returns the value of the '<em><b>Stoppingcriteria</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stoppingcriteria</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stoppingcriteria</em>' reference.
   * @see #setStoppingcriteria(Stopping_Criteria)
   * @see org.xtext.example.opt.opt.OptPackage#getOptimizer_Stoppingcriteria()
   * @model
   * @generated
   */
  Stopping_Criteria getStoppingcriteria();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Optimizer#getStoppingcriteria <em>Stoppingcriteria</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stoppingcriteria</em>' reference.
   * @see #getStoppingcriteria()
   * @generated
   */
  void setStoppingcriteria(Stopping_Criteria value);

  /**
   * Returns the value of the '<em><b>Optimizationmethod</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Optimizationmethod</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optimizationmethod</em>' reference.
   * @see #setOptimizationmethod(OptimizationMethod)
   * @see org.xtext.example.opt.opt.OptPackage#getOptimizer_Optimizationmethod()
   * @model
   * @generated
   */
  OptimizationMethod getOptimizationmethod();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Optimizer#getOptimizationmethod <em>Optimizationmethod</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Optimizationmethod</em>' reference.
   * @see #getOptimizationmethod()
   * @generated
   */
  void setOptimizationmethod(OptimizationMethod value);

  /**
   * Returns the value of the '<em><b>Seed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seed</em>' attribute.
   * @see #setSeed(int)
   * @see org.xtext.example.opt.opt.OptPackage#getOptimizer_Seed()
   * @model
   * @generated
   */
  int getSeed();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Optimizer#getSeed <em>Seed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seed</em>' attribute.
   * @see #getSeed()
   * @generated
   */
  void setSeed(int value);

  /**
   * Returns the value of the '<em><b>Minmax</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.opt.opt.MinMax}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minmax</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minmax</em>' attribute.
   * @see org.xtext.example.opt.opt.MinMax
   * @see #setMinmax(MinMax)
   * @see org.xtext.example.opt.opt.OptPackage#getOptimizer_Minmax()
   * @model
   * @generated
   */
  MinMax getMinmax();

  /**
   * Sets the value of the '{@link org.xtext.example.opt.opt.Optimizer#getMinmax <em>Minmax</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minmax</em>' attribute.
   * @see org.xtext.example.opt.opt.MinMax
   * @see #getMinmax()
   * @generated
   */
  void setMinmax(MinMax value);

} // Optimizer
