/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.opt.opt;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stopping Criteria</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.opt.opt.OptPackage#getStopping_Criteria()
 * @model
 * @generated
 */
public interface Stopping_Criteria extends EObject
{
} // Stopping_Criteria
